name: Slack notifications
on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:
jobs:
  run:
    name: Send notifications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Download previous test output file
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: security-tests.yml
          name: security-test-output
          path: .
        continue-on-error: false       
        
      - name: Parse test results for slack notification
        id: parse-results-for-slack
        if: always() #&& github.ref == 'refs/heads/main'
        run: |
          FAILURE_COUNT=$(grep -oP '\d+(?= failed)' test_output.log | head -1)
          echo "failure_count=${FAILURE_COUNT:-0}" >> $GITHUB_ENV
        
      - name: Share recent changes with a channel
        if: always() && (steps.parse-results-for-slack.outcome == 'success') #&& github.ref == 'refs/heads/main'
        uses: slackapi/slack-github-action@v3.0.1
        with:
          webhook: "SLACK_NOTIFICATION_WEBHOOK_URL"
          webhook-type: webhook-trigger
          payload: |
            {"failure_count": "${{ env.failure_count }}"}
